name: Atualizar Linguagens no README

on:
  schedule:
    - cron: '0 0 * * 0'  # Executa uma vez por semana (todo domingo à meia-noite)
  workflow_dispatch: # Permite disparar manualmente

jobs:
  update_readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configuração do Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Rodar o script Python
        run: |
          python linguagens_github.py

      - name: Commit e push do README.md
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add linguagens_porcentagem.md
          git commit -m "Atualizar porcentagens de linguagens no README"
          git push
